# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

# See docs at https://www.packer.io/docs/install/index.html
steps:
- name: 'gcr.io/cloud-builders/wget'
  args: ["https://releases.hashicorp.com/packer/${_PACKER_VERSION}/packer_${_PACKER_VERSION}_linux_amd64.zip"]
  id: 'fetch-packer'
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/packer:${_PACKER_VERSION}',
        '-t', 'gcr.io/$PROJECT_ID/packer',
        '--build-arg', 'PACKER_VERSION=${_PACKER_VERSION}',
        '--build-arg', 'PACKER_VERSION_SHA256SUM=${_PACKER_VERSION_SHA256SUM}',
        '.']
  waitFor: ['fetch-packer']
  id: 'build-docker-image'      
  
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', 'mkdir ~/.config ; mkdir ~/.config/gcloud ; gcloud secrets versions access latest --secret=${_SECRET_MANAGER_NAME} --project=${_SECRET_MANAGER_PROJECT} > ~/.config/gcloud/application_default_credentials.json' ]
  waitFor: ['fetch-packer', 'build-docker-image']
  id: 'get-serviceaccount'

- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', 'pwd ; ls -al modules/config ; cp -f ~/.config/gcloud/application_default_credentials.json ~/modules/config/sa-kms-unseal.json ; ls -al modules/config' ]
  waitFor: ['fetch-packer', 'build-docker-image', 'get-serviceaccount']
  id: 'get-unseal-serviceaccount'
  
- name: 'gcr.io/$PROJECT_ID/packer'
  args:
  - build
  - -debug
  - -var
  - project_id=$PROJECT_ID
  - vault.json
  waitFor: ['fetch-packer', 'build-docker-image', 'get-serviceaccount', 'get-unseal-serviceaccount']
  id: 'build-vault-golden-image'
tags: ['cloud-builders-community']
  
substitutions:
  _PACKER_VERSION: 1.7.3
  _PACKER_VERSION_SHA256SUM: 1a8719f0797e9e45abd98d2eb38099b09e5566ec212453052d2f21facc990c73
  _SECRET_MANAGER_NAME: packer-sa
  
images:
- 'gcr.io/$PROJECT_ID/packer:latest'
- 'gcr.io/$PROJECT_ID/packer:$_PACKER_VERSION'
tags: ['cloud-builders-community']
